### ISSUE TITLE
sites.google.com doesn't render webm file directly

### ISSUE THREAD

**Issue by shhnjk** [shravanrn/LibrarySandboxing#2]
From the paper:

> For many sites, Trudy might not even need to upload malicious content to the (trusted) victim origin (sites.google.com in our example).

`sites.google.com` renders untrusted content inside `https://www.gstatic.com` iframe. I do not see `.webm` being loaded directly into `sites.google.com`. Could you share an example site where it does this?

**Comment by deian** [comment]
Can you give this a shot: https://sites.google.com/eng.ucsd.edu/rlbox-site-isolation-demo

We'll clean up this page/example (and some other ones we've played with) with the final version of the paper.

**Comment by shhnjk** [comment]
Video and audio are served from either `googleusercontent.com` iframe or `drive.google.com` iframe. But I don't see your claim that attacker's `.webm` file is rendered in `sites.google.com`. Could you explain?

**Comment by deian** [comment]
The drive.google.com and sites.google.com are same site, no?

I'd love to clean up this example to both be precise and more clear so really appreciate you bringing this up!

**Comment by shhnjk** [comment]
Have you confirmed that content uploaded to `drive.google.com` is never converted to a safe format? Those site usually convert video and audio, for both security and compression purposes.

**Comment by deian** [comment]
Yep (pg 12, section 7.1); they re-encode images but not video and audio (at least not the ogg and vpx we tested).

**Comment by shhnjk** [comment]
Okay, that's fair then :)
Thanks for the clarification :)

**Comment by deian** [comment]
Thank you! :)
