### ISSUE TITLE
Error while running make

### ISSUE THREAD

**Issue by sbairoliya** [shravanrn/LibrarySandboxing#3]
When I run make I get the following error. I am using a fresh VM with Ubuntu 18.04LTS, 32 GB RAM, 4 cores. This indicates an invalid conversion from const unsigned char*’ to ‘unsigned char*’.

In file included from /home/shivam/LibrarySandboxing/ffbuilds/firefox_64bit_optdebug_static/dom/media/platforms/Unified_cpp_dom_media_platforms0.cpp:65:0:
19:41.97 /home/shivam/LibrarySandboxing/mozilla-release/dom/media/platforms/agnostic/VPXDecoder.cpp: In member function ‘mozilla::MediaResult mozilla::VPXDecoder::DecodeAlpha(vpx_image_t**, const mozilla::MediaRawData*)’:
19:41.97 /home/shivam/LibrarySandboxing/mozilla-release/dom/media/platforms/agnostic/VPXDecoder.cpp:552:30: error: invalid conversion from ‘const unsigned char*’ to ‘unsigned char*’ [-fpermissive]
19:41.97    unsigned char* buff_copy = aData;
19:41.97                               ^~~~~
19:43.47 /home/shivam/LibrarySandboxing/mozilla-release/config/rules.mk:1065: recipe for target 'Unified_cpp_dom_media_platforms0.o' failed
19:43.47 make[6]: *** [Unified_cpp_dom_media_platforms0.o] Error 1
19:43.47 /home/shivam/LibrarySandboxing/mozilla-release/config/recurse.mk:73: recipe for target 'dom/media/platforms/target' failed
19:43.47 make[5]: *** [dom/media/platforms/target] Error 2
19:43.47 make[5]: *** Waiting for unfinished jobs....
19:45.65 libdom_media.a.desc
19:47.53 libdom_media_ipc.a.desc
19:48.23 libdom_media_platforms_agnostic_gmp.a.desc
19:49.05 libdom_media_platforms_agnostic_eme.a.desc
19:49.07 libdom_media_ogg.a.desc
19:49.08 libdom_media_mediasource.a.desc
19:49.13 /home/shivam/LibrarySandboxing/mozilla-release/config/recurse.mk:32: recipe for target 'compile' failed
19:49.13 make[4]: *** [compile] Error 2
19:49.13 /home/shivam/LibrarySandboxing/mozilla-release/config/rules.mk:452: recipe for target 'default' failed
19:49.13 make[3]: *** [default] Error 2
19:49.13 /home/shivam/LibrarySandboxing/mozilla-release/client.mk:424: recipe for target 'realbuild' failed
19:49.13 make[2]: *** [realbuild] Error 2
19:49.14 client.mk:175: recipe for target 'build' failed
19:49.14 make[1]: *** [build] Error 2
19:49.14 0 compiler warnings present.
19:49.16 /usr/bin/notify-send --app-name=Mozilla Build System Mozilla Build System Build failed
Makefile:103: recipe for target 'static64' failed
make: *** [static64] Error 2

I fixed this by typecasting when trying to run RLBox on Firefox

**Comment by deian** [comment]
Are you sandboxing vpx? Can't quite tell where rlbox comes into play

**Comment by sbairoliya** [comment]
I was just trying to reproduce the results in the paper and want to run the Process Sandbox, this the error I got when I ran make. I was just notifying the authors thinking that this might be a potential bug.

**Comment by deian** [comment]
Ah! Sorry I just noticed now what repo you're commenting on :) I'll let Shravan and/or Craig respond

**Comment by shravanrn** [comment]
@sbairoliya: I just responded to your email about the process sandbox, so that should give you next steps for debugging.

Re the above, yeah that fix makes sense. Depending on the exact details of compiler and platform exactly what gets classified as an error and what is a warning changes. Surprising that we didn't run into it ourselves given that you appear to be using a standard platform. Anyway let me know if you run into any other issues. Feel free to submit a PR on the above

**Comment by sbairoliya** [comment]
I submitted a pul request. Thanks for being prompt.
